services:
  database:
    image: alvildaaa/instagrimdb
    hostname: database

  webapp:
    image: alvildaaa/instagrimapp
    restart: on-failure
    hostname: instagrim
    networks:
      - default
    ports:
      - '8080:8080'

networks:
  default:
    internal: true
